theme: minima
title: My Journal of Learning
author: GitHub User
email: vijay@alagappan.com
description: > # this means to ignore newlines until "baseurl:"
  A Blog by Vijay Alagappan to record and share his learnings

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  vjmechwiz # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
